export {
  createAgentIdentity,
  createPrincipalIdentity,
  createPublisherIdentity,
  createDomainVerificationChallenge,
  createOrganizationDomainVerificationChallenge,
  createPasskeyAuthenticationChallenge,
  createPasskeyRegistrationChallenge,
  createTrustAnchorDistribution,
  didFromPublicKey,
  isValidFidesDid,
  publicKeyFromDid,
  verifyDomainDid,
  verifyOrganizationDomainDid,
  verifyPasskeyAuthentication,
  verifyPasskeyRegistration,
  type AgentIdentity,
  type GovernedTrustAnchor,
  type IdentityTrustAnchor,
  type PrincipalIdentity,
  type PublisherIdentity,
  type TrustAnchor,
  type TrustAnchorType,
} from '@fides/core'
