export {
  classifyCapabilityRisk,
  createCapabilityDescriptor,
  findCapabilityOntologyEntry,
  normalizeAgentCard,
  parseCapabilityId,
  signAgentCard,
  validateAgentCard,
  verifySignedAgentCard,
  verifySignedAgentCardIdentity,
  type AgentCard,
  type CapabilityControl,
  type CapabilityDescriptor,
  type CapabilityOntologyEntry,
  type EndpointDescriptor,
  type PolicyRequirement,
  type SignedAgentCard,
  type TransportDescriptor,
} from '@fides/core'
