export const ALGORITHM = 'ed25519' as const
export const SIGNATURE_HEADER = 'signature' as const
export const SIGNATURE_INPUT_HEADER = 'signature-input' as const
export const WELL_KNOWN_PATH = '/.well-known/fides.json' as const
export const DEFAULT_TRUST_DECAY = 0.85
export const MAX_TRUST_DEPTH = 6
export const DEFAULT_SIGNATURE_EXPIRY_SECONDS = 300
export const DID_METHOD = 'fides' as const
export const DID_PREFIX = `did:${DID_METHOD}:` as const
